// Generated by CoffeeScript 1.6.2
/* Integrator
*/

var Integrator;

Integrator = (function() {
  function Integrator() {}

  Integrator.prototype.integrate = function(particles, dt) {};

  return Integrator;

})();
