// Generated by CoffeeScript 1.4.0
/* Integrator
*/

var Integrator;

Integrator = (function() {

  function Integrator() {}

  Integrator.prototype.integrate = function(particles, dt) {};

  return Integrator;

})();
