// Generated by CoffeeScript 1.4.0
/* Collision Behaviour
*/

var Collision;

Collision = {
  apply: function(p1, p2, useMass) {
    var delta, dist, distSq, mt, overlap, r1, r2, radii;
    if (useMass == null) {
      useMass = true;
    }
    delta = Vector.sub(p2.pos, p1.pos);
    distSq = delta.magSq();
    radii = p1.radius + p2.radius;
    if (distSq <= radii * radii) {
      dist = Math.sqrt(distSq);
      overlap = (p1.radius + p2.radius) - dist;
      overlap += 0.5;
      mt = p1.mass + p2.mass;
      r1 = useMass ? p2.mass / mt : 0.5;
      r2 = useMass ? p1.mass / mt : 0.5;
      p1.pos.add(delta.clone().norm().scale(overlap * -r1));
      return p2.pos.add(delta.norm().scale(overlap * r2));
    }
  }
};
